---
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - .env
      - .env.local
    restart: unless-stopped
    tty: true
    ports:
      - "8000:8080"
    volumes:
      - ./app:/var/www/app
      - ./config:/var/www/config
      - ./database:/var/www/database
      - ./resources:/var/www/resources
      - ./routes:/var/www/routes
      - ./tests:/var/www/tests
      - ./phpunit.xml:/var/www/phpunit.xml
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./.env:/var/www/.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:alpine
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  dbdata:
